#
# Spydr06's starship configuration
# https://github.com/spydr06/dotfiles.git
#

format = """
[╭─](white)$directory$time $git_branch$git_commit$git_state$git_status$package$cmake$dart$dotnet$premake$golang$java$kotlin$nodejs$perl$php$python$ruby$rust
[╰──>](white) $username $character
"""

[character]
success_symbol = "[>](green)[>](bold blue)[>](green)"
error_symbol = "[>](red)[>](bold yellow)[>](red)"

[directory]
truncation_length = 32
truncation_symbol = ""
truncate_to_repo = true 
format = '[\[](white)[$path](bold blue)[$read_only](bold red)[\]](white)'

[time]
disabled = true
format = '[at $time](white)'
time_format = "%T"
utc_time_offset = "1"
time_range = "00:00:00-24:00:00"

[username]
disabled = false
show_always = true
style_user = "white bold"
style_root = "red bold"
format = "[λ]($style) [/](bold blue)"

[java]
symbol = "Java "
