# disable empty line when opening new prompt
# add_newline = false
# format = """
# $time\
# $hostname\
# $shlvl\
# $kubernetes\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $dart\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $ruby\
# $rust\
# $swift\
# $terraform\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $lua\
# $jobs\
# $battery\
# $status
# $username\
# $character
# """

programming_languages = """
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
"""

format = """
[┌─](white)$directory$time $git_branch$git_commit$git_state$git_status$package$cmake$dart$dotnet$premake$golang$java$kotlin$nodejs$perl$php$python$ruby$rust
[└──>](white) $username $character
"""

[premake]
disabled = false
format = "[using](white) [premake5](bold green)"

[dotnet]
disabled = true
style = "blue"
heuristic = true
format = '[via](white) [VS Project](blue) [\(.NET\)](blue bold)'

[character]
success_symbol = "[>](green)[>](bold blue)[>](green)"
error_symbol = "[>](red)[>](bold yellow)[>](red)"

[directory]
truncation_length = 32
truncation_symbol = ""
truncate_to_repo = true 
format = '[\[](white)[$path](bold blue)[$read_only](bold red)[\]](white)'

[time]
disabled = true
format = '[at $time](white)'
time_format = "%T"
utc_time_offset = "1"
time_range = "00:00:00-24:00:00"

[username]
disabled = false
show_always = true
style_user = "white bold"
style_root = "yellow bold"
format = "[λ]($style) [/](bold blue)"

[java]
symbol = "Java "
