#!/bin/bash

#
# Spydr06's bspwm configuration
# https://gihub.com/spydr06/dotfiles.git
#

#
# Autostart Applications
#

## x11 settings ##
xrandr --dpi 96 & # set the dpi
setxkbmap "de(us)" &    # set the keyboard layout to default German
sxhkd &           # start the hotkey daemon

## start parts of the lxqt-desktop environment for convenience ##
lxpolkit &
gnome-keyring-daemon &

light-locker --lock-on-suspend & # return to lightdm when the computer gets suspended

xset s 0 0 # disable burn-in prevention

## look and feel ##
nitrogen --restore &                      # apply the wallpaper
picom --vsync &   # enable compositor
~/.config/polybar/launch.sh &             # start the bar
eww daemon

# conky --config=$HOME/.config/conky.conf & # start the conky panel


#
# BSPWM Settings
#

## monitor workspaces ##
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0

## window layout ##
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5 # split windows at half of their size
bspc config rounded_corners 10

## window behavior ##
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## mouse behavior ##
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config poiner_follows_monitor true
bspc config pointer_modifier mod4			# set the mouse pointer modifier to be the super key
bspc config pointer_action1 move          	# move a window using super+left mouse button
bspc config pointer_action3 resize_corner	# resize a window using super+right mouse button
bspc config pointer_motion_interval 1

## border colors ##
bspc config normal_border_color \#000000
bspc config active_border_color \#000000
bspc config focused_border_color \#446382 #\#446dba #\#516C76

## application rules ##
bspc rule -a Gimp                desktop='^6' follow=on
bspc rule -a firefox             desktop="^3" follow=on
bspc rule -a Spotify             desktop='^5' follow=on
bspc rule -a discord             desktop='^4' follow=on
bspc rule -a Nitrogen            state=floating
bspc rule -a Emacs               state=tiled
bspc rule -a mpv                 state=floating
bspc rule -a qemu-system-x86_64  state=floating
bspc rule -a qemu-system-aarch64 state=floating
bspc rule -a qemu-system-i386    state=floating
bspc rule -a logicrs             state=floating
bspc rule -a client              state=floating
